### ISSUE TITLE
Custom predictors with additional variables that unrelated to time series

### ISSUE THREAD

**Issue by oy321** [JoaquinAmatRodrigo/skforecast#124] opened 2022-03-21 10:06 UTC
Thanks for the great library! I am trying to apply it to a use case where I need to train a predictor to make a recursive multi-step predictions into the future, where I'd wish to use multiple predicting variables that not related to the target time series itself, but it seems impossible.

First I am aware of the exogenous variables but it requires the future values of exogenous variables are known. In my case, as I need the final forecaster to be able to make multi-steps prediction into future, so this function is not relevant.

For the 'ForecasterAutoregCustom' function where it supports argument of 'fun_predictors', I looked at the source code line 246: 
   X_train.append(self.create_predictors(y=y_values[train_index]))

It only takes the "y" values as the input but not the other variables that not related to "y". Well, it's very common to have a multi-variate and multi-step forecasting scenario when the future exogenous variables are unknown, I am not quite sure how to do it with this library.

Thank you

**Comment by JoaquinAmatRodrigo** [comment] 2022-03-21 22:14
Hi @oy321 
If I do understood your explanation, you are trying to train a forecaster using multiple time series at once.
This feature is not yet available, but will be in the 0.5 release, that I hope will be release soon.

**Comment by JoaquinAmatRodrigo** [comment] 2022-03-22 08:40
This is something already demanded by several users so it will be one of the priorities for next release. @JavierEscobarOrtiz let's keep in mind.

**Comment by oy321** [comment] 2022-03-22 22:39
That's great. Please let me know if I can be of any help. Excuse me from going further on this topic, would this new feature support multi-step **recursive** predictions with multiple time series inputs, or only the **direct** predictions using multiple models?

**Comment by JoaquinAmatRodrigo** [comment] 2022-03-23 08:43
The idea I have so fare is to generalizer the input `y` in a way that it allows using dataframes. Each column of the dataframe will be considered as independent time series from which the forecaster will learn. This approach should be compatible with both, multi-step recursive and multi-step direct. I will share an initial draft as soon as possible :-)

**Comment by oy321** [comment] 2022-03-23 20:17
Thanks for sharing the details. I could imagine the way you described as "each column of the dataframe will be considered as independent time series from which the forecaster will learn". However I have a doubt of how it could work with multi-step recursive forecasting. When there is only one predictor which is the target 'y', the recursive strategy works. But with multiple time series inputs, you can make prediction on the next step of target 'y', but then the following steps would require the other input time series in the future steps too which would be not available. Therefore I thought only the multi-step direct approach is possible?

**Comment by JoaquinAmatRodrigo** [comment] 2022-03-24 09:23
You are right @oy321 
I will do some research about how multiple time series may be used in a multi-step recursive strategy but, as you explained, it may be only possible for multi-step direct approach.  Thanks a lot for sharing your thoughts, any new idea is very welcome!

**Comment by oy321** [comment] 2022-03-26 13:28
My pleasure! Would get in touch if there is any. And please let me know if I am proved wrong re. above.

**Comment by JoaquinAmatRodrigo** [comment] 2022-09-24 09:30
New feature for multi-series forecasting has been added in version 0.5.0

https://joaquinamatrodrigo.github.io/skforecast/0.5.0/user_guides/multi-time-series-forecasting.html

**Comment by pmateosmasa1** [comment] 2022-10-05 15:09
Hi, first of all congrats for your incredible library, awesome work! I have been exploring the latest features in 0.5.0 and specially the Multi Time Series forecasting. 
One question arised was about the idea of Multivariate Multi time series ones. 
Due to the recursive way isn't possible because the interdependencies between targets and lagged features, the only way to deal with this problem would be the direct approach, right? I guess using the MultiOutput function.

**Comment by JoaquinAmatRodrigo** [comment] 2022-10-10 08:42
Hi @pmateosmasa1,
You are right, for multivariate time series forecasting, the aproach we are working on is by using the Direct strtategy. However, there are also other models that are able to handle multivariate scenarios, one of them is Vector Autoregression (VAR).
 
https://www.machinelearningplus.com/time-series/vector-autoregression-examples-python/

**Comment by JavierEscobarOrtiz** [comment] 2022-12-01 11:18
Hi @pmateosmasa1 

Multivariate approach has been released in skforecast 0.6.0 😄 Check the user guide:

https://joaquinamatrodrigo.github.io/skforecast/latest/user_guides/multivariate-forecasting.html

**Comment by JoaquinAmatRodrigo** [comment] 2023-04-05 09:56
It has been more than 60 days since the last activity on this GitHub issue. Since we have not received any updates or progress reports, we will be closing this issue.

If this issue is still relevant and requires attention, please feel free to reopen it and provide an update. We appreciate your contributions and would love to see this issue resolved if it is still relevant.

Thank you for your participation and cooperation!

**Closed by JoaquinAmatRodrigo** 2023-04-05 09:56 UTC
Labels: question
