### ISSUE TITLE
fcaster.fit Lightgmb freezes

### ISSUE THREAD

**Issue by tulbureandreit** [JoaquinAmatRodrigo/skforecast#318] opened 2022-12-19 13:09 UTC
Hi,

To be very short:

I tried to fit a lightgbm model onto forecaster and it freezes every time without RAM or memory issues.

Code:

```
param_grid = {'n_estimators': 2000, 'boosting_type': 'dart', 'max_depth': 45, 'learning_rate': 0.01, 'num_leaves': 25, 'lambda_l1': 0.1, 'lambda_l2': 0.5, 'min_child_samples': 50}

  lags_lightgbm = 16
  forecaster = ForecasterAutoreg(
      regressor=LGBMRegressor(**param_grid), lags=lags_lightgbm
  )
  cols = [col for col in df_to_process_lightgbm.columns if col not in ["ds", "y"]]

  exog = df_to_process_lightgbm[cols]

  forecaster.fit(y=df_to_process_lightgbm["y"], exog=exog) -> here it freezes

  predictions = forecaster.predict(steps=8, exog=exog)

  predictions = predictions.values
```

Environment: Ubuntu 20.04

```
certifi                  2022.9.24
charset-normalizer       2.1.1
click                    8.1.3
cliff                    4.1.0
cmaes                    0.9.0
cmd2                     2.4.2
cmdstanpy                1.0.8
colorlog                 6.7.0
comm                     0.1.2
contourpy                1.0.6
convertdate              2.4.0
cycler                   0.11.0
Cython                   0.29.32
debugpy                  1.6.4
decorator                5.1.1
entrypoints              0.4
ephem                    4.1.3
executing                1.2.0
fonttools                4.38.0
frozenlist               1.3.3
greenlet                 2.0.1
hijri-converter          2.2.4
idna                     3.4
importlib-metadata       5.1.0
ipykernel                6.19.2
ipython                  8.7.0
ipywidgets               8.0.3
isoweek                  1.3.3
jedi                     0.18.2
jmespath                 1.0.1
joblib                   1.2.0
kiwisolver               1.4.4
lightgbm                 3.3.3
LunarCalendar            0.0.9
Mako                     1.2.4
MarkupSafe               2.1.1
matplotlib               3.5.0
matplotlib-inline        0.1.6
multidict                6.0.2
mypy-extensions          0.4.3
mysql-connector-python   8.0.31
nest-asyncio             1.5.6
numpy                    1.23.0
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
optuna                   2.10.0
packaging                22.0
pandas                   1.4.0
parso                    0.8.3
pathspec                 0.10.2
patsy                    0.5.3
pbr                      5.11.0
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.3.0
pip                      22.3.1
platformdirs             2.6.0
prettytable              3.5.0
prompt-toolkit           3.0.36
protobuf                 3.20.1
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
pyaml                    21.10.1
Pygments                 2.13.0
PyMeeus                  0.5.12
pyparsing                3.0.9
pyperclip                1.8.2
python-dateutil          2.8.2
python-slugify           6.1.2
pytz                     2022.6
PyYAML                   6.0
pyzmq                    24.0.1
s3transfer               0.6.0
scikit-learn             1.1.0
scikit-optimize          0.9.0
scipy                    1.9.3
seaborn                  0.11.0
setuptools               65.6.3
setuptools-git           1.2
setuptools-scm           7.0.5
six                      1.16.0
skforecast               0.5.1
stack-data               0.6.2
statsmodels              0.13.0
stevedore                4.1.1
tenacity                 8.1.0
text-unidecode           1.3
threadpoolctl            3.1.0
tomli                    2.0.1
torch                    1.12.0
torch-lr-finder          0.2.1
tornado                  6.2
tqdm                     4.64.0
traitlets                5.7.1
typing_extensions        4.4.0
urllib3                  1.26.13
wcwidth                  0.2.5
wheel                    0.38.4
widgetsnbextension       4.0.4
yarl                     1.8.1
```

**Comment by JoaquinAmatRodrigo** [comment] 2022-12-19 13:40
Hi @tulbureandreit 

I would suggest reducing the value of 'n_estimators' and seeing if it freezes. If not, then the problem is that the lightgbm model is taking a long time to train due to the high amount of estimators included.

Best

**Comment by tulbureandreit** [comment] 2022-12-19 14:40
@JoaquinAmatRodrigo  it is not frozen, it just takes a lot to fit, although I have a very performant workstation

-> on another pc, that has the same env, it takes only about 30 sec with 2000 estimators 

I do not quite get the issue here, why did it change. Like a week ago this same env and application took only about 20-30 sec to fit. Weird

**Comment by JoaquinAmatRodrigo** [comment] 2023-04-05 10:14
Hi, 
It has been more than 60 days since the last activity on this GitHub issue. Since we have not received any updates or progress reports, we will be closing this issue.

If this issue is still relevant and requires attention, please feel free to reopen it and provide an update. We appreciate your contributions and would love to see this issue resolved if it is still relevant.

Thank you for your participation and cooperation!

**Closed by JoaquinAmatRodrigo** 2023-04-05 10:14 UTC
